services:
  frontend:
    build:
      context: ./HJ-DEV/frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:5173",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - havjeang-network

  backend:
    build:
      context: ./HJ-DEV
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - havjeang-network
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - havjeang-network

networks:
  havjeang-network:
    driver: bridge

volumes:
  db_data:
