name: CD Workflow

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start containers
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

      - name: Stop containers
        if: always()
        run: docker-compose down
